import Cookies from 'js-cookie'
class Country {
  constructor () {
    this.nation = [
      {code: 'HK', en: 'Hong Kong', zh: '香港'},
      {code: 'TW', en: 'Taiwan', zh: '台湾'},
      {code: 'MO', en: 'Macao', zh: '澳门'},
      {code: 'US', en: 'United States of America (USA)', zh: '美国'},
      {code: 'AR', en: 'Argentina', zh: '阿根廷'},
      {code: 'AD', en: 'Andorra', zh: '安道尔'},
      {code: 'AE', en: 'United Arab Emirates', zh: '阿联酋'},
      {code: 'AF', en: 'Afghanistan', zh: '阿富汗'},
      {code: 'AG', en: 'Antigua & Barbuda', zh: '安提瓜和巴布达'},
      {code: 'AI', en: 'Anguilla', zh: '安圭拉'},
      {code: 'AL', en: 'Albania', zh: '阿尔巴尼亚'},
      {code: 'AM', en: 'Armenia', zh: '亚美尼亚'},
      {code: 'AO', en: 'Angola', zh: '安哥拉'},
      {code: 'AQ', en: 'Antarctica', zh: '南极洲'},
      {code: 'AS', en: 'American Samoa', zh: '美属萨摩亚'},
      {code: 'AT', en: 'Austria', zh: '奥地利'},
      {code: 'AU', en: 'Australia', zh: '澳大利亚'},
      {code: 'AW', en: 'Aruba', zh: '阿鲁巴'},
      {code: 'AX', en: 'Aland Island', zh: '奥兰群岛'},
      {code: 'AZ', en: 'Azerbaijan', zh: '阿塞拜疆'},
      {code: 'BA', en: 'Bosnia & Herzegovina', zh: '波黑'},
      {code: 'BB', en: 'Barbados', zh: '巴巴多斯'},
      {code: 'BD', en: 'Bangladesh', zh: '孟加拉'},
      {code: 'BE', en: 'Belgium', zh: '比利时'},
      {code: 'BF', en: 'Burkina', zh: '布基纳法索'},
      {code: 'BG', en: 'Bulgaria', zh: '保加利亚'},
      {code: 'BH', en: 'Bahrain', zh: '巴林'},
      {code: 'BI', en: 'Burundi', zh: '布隆迪'},
      {code: 'BJ', en: 'Benin', zh: '贝宁'},
      {code: 'BL', en: 'Saint Barthélemy', zh: '圣巴泰勒米岛'},
      {code: 'BM', en: 'Bermuda', zh: '百慕大'},
      {code: 'BN', en: 'Brunei', zh: '文莱'},
      {code: 'BO', en: 'Bolivia', zh: '玻利维亚'},
      {code: 'BQ', en: 'Caribbean Netherlands', zh: '荷兰加勒比区'},
      {code: 'BR', en: 'Brazil', zh: '巴西'},
      {code: 'BS', en: 'The Bahamas', zh: '巴哈马'},
      {code: 'BT', en: 'Bhutan', zh: '不丹'},
      {code: 'BV', en: 'Bouvet Island', zh: '布韦岛'},
      {code: 'BW', en: 'Botswana', zh: '博茨瓦纳'},
      {code: 'BY', en: 'Belarus', zh: '白俄罗斯'},
      {code: 'BZ', en: 'Belize', zh: '伯利兹'},
      {code: 'CA', en: 'Canada', zh: '加拿大'},
      {code: 'CC', en: 'Cocos (Keeling) Islands', zh: '科科斯群岛'},
      {code: 'CD', en: 'Democratic Republic of the Congo', zh: '刚果（金）'},
      {code: 'CF', en: 'Central African Republic', zh: '中非'},
      {code: 'CG', en: 'Republic of the Congo', zh: '刚果（布）'},
      {code: 'CH', en: 'Switzerland', zh: '瑞士'},
      {code: 'CI', en: 'Cote d"Ivoire', zh: '科特迪瓦'},
      {code: 'CK', en: 'Cook Islands', zh: '库克群岛'},
      {code: 'CL', en: 'Chile', zh: '智利'},
      {code: 'CM', en: 'Cameroon', zh: '喀麦隆'},
      {code: 'zh', en: 'China', zh: '中国'},
      {code: 'CO', en: 'Colombia', zh: '哥伦比亚'},
      {code: 'CR', en: 'Costa Rica', zh: '哥斯达黎加'},
      {code: 'CU', en: 'Cuba', zh: '古巴'},
      {code: 'CV', en: 'Cape Verde', zh: '佛得角'},
      {code: 'CW', en: 'Curacao', zh: '库拉索'},
      {code: 'CX', en: 'Christmas Island', zh: '圣诞岛'},
      {code: 'CY', en: 'Cyprus', zh: '塞浦路斯'},
      {code: 'CZ', en: 'Czech Republic', zh: '捷克'},
      {code: 'DE', en: 'Germany', zh: '德国'},
      {code: 'DJ', en: 'Djibouti', zh: '吉布提'},
      {code: 'DK', en: 'Denmark', zh: '丹麦'},
      {code: 'DM', en: 'Dominica', zh: '多米尼克'},
      {code: 'DO', en: 'Dominican Republic', zh: '多米尼加'},
      {code: 'DZ', en: 'Algeria', zh: '阿尔及利亚'},
      {code: 'EC', en: 'Ecuador', zh: '厄瓜多尔'},
      {code: 'EE', en: 'Estonia', zh: '爱沙尼亚'},
      {code: 'EG', en: 'Egypt', zh: '埃及'},
      {code: 'EH', en: 'Western Sahara', zh: '西撒哈拉'},
      {code: 'ER', en: 'Eritrea', zh: '厄立特里亚'},
      {code: 'ES', en: 'Spain', zh: '西班牙'},
      {code: 'ET', en: 'Ethiopia', zh: '埃塞俄比亚'},
      {code: 'FI', en: 'Finland', zh: '芬兰'},
      {code: 'FJ', en: 'Fiji', zh: '斐济群岛'},
      {code: 'FK', en: 'Falkland Islands', zh: '马尔维纳斯群岛（福克兰）'},
      {code: 'FM', en: 'Federated States of Micronesia', zh: '密克罗尼西亚联邦'},
      {code: 'FO', en: 'Faroe Islands', zh: '法罗群岛'},
      {code: 'FR', en: 'France', zh: '法国 法国'},
      {code: 'GA', en: 'Gabon', zh: '加蓬'},
      {code: 'GB', en: 'Great Britain (United Kingdom; England)', zh: '英国'},
      {code: 'GD', en: 'Grenada', zh: '格林纳达'},
      {code: 'GE', en: 'Georgia', zh: '格鲁吉亚'},
      {code: 'GF', en: 'French Guiana', zh: '法属圭亚那'},
      {code: 'GG', en: 'Guernsey', zh: '根西岛'},
      {code: 'GH', en: 'Ghana', zh: '加纳'},
      {code: 'GI', en: 'Gibraltar', zh: '直布罗陀'},
      {code: 'GL', en: 'Greenland', zh: '格陵兰'},
      {code: 'GM', en: 'Gambia', zh: '冈比亚'},
      {code: 'GN', en: 'Guinea', zh: '几内亚'},
      {code: 'GP', en: 'Guadeloupe', zh: '瓜德罗普'},
      {code: 'GQ', en: 'Equatorial Guinea', zh: '赤道几内亚'},
      {code: 'GR', en: 'Greece', zh: '希腊'},
      {code: 'GS', en: 'South Georgia and the South Sandwich Islands', zh: '南乔治亚岛和南桑威奇群岛'},
      {code: 'GT', en: 'Guatemala', zh: '危地马拉'},
      {code: 'GU', en: 'Guam', zh: '关岛'},
      {code: 'GW', en: 'Guinea-Bissau', zh: '几内亚比绍'},
      {code: 'GY', en: 'Guyana', zh: '圭亚那'},
      {code: 'HM', en: 'Heard Island and McDonald Islands', zh: '赫德岛和麦克唐纳群岛'},
      {code: 'HN', en: 'Honduras', zh: '洪都拉斯'},
      {code: 'HR', en: 'Croatia', zh: '克罗地亚'},
      {code: 'HT', en: 'Haiti', zh: '海地'},
      {code: 'HU', en: 'Hungary', zh: '匈牙利'},
      {code: 'ID', en: 'Indonesia', zh: '印尼'},
      {code: 'IE', en: 'Ireland', zh: '爱尔兰'},
      {code: 'IL', en: 'Israel', zh: '以色列'},
      {code: 'IM', en: 'Isle of Man', zh: '马恩岛'},
      {code: 'IN', en: 'India', zh: '印度'},
      {code: 'IO', en: 'British Indian Ocean Territory', zh: '英属印度洋领地'},
      {code: 'IQ', en: 'Iraq', zh: '伊拉克'},
      {code: 'IR', en: 'Iran', zh: '伊朗'},
      {code: 'IS', en: 'Iceland', zh: '冰岛'},
      {code: 'IT', en: 'Italy', zh: '意大利'},
      {code: 'JE', en: 'Jersey', zh: '泽西岛'},
      {code: 'JM', en: 'Jamaica', zh: '牙买加'},
      {code: 'JO', en: 'Jordan', zh: '约旦'},
      {code: 'JP', en: 'Japan', zh: '日本'},
      {code: 'KE', en: 'Kenya', zh: '肯尼亚'},
      {code: 'KG', en: 'Kyrgyzstan', zh: '吉尔吉斯斯坦'},
      {code: 'KH', en: 'Cambodia', zh: '柬埔寨'},
      {code: 'KI', en: 'Kiribati', zh: '基里巴斯'},
      {code: 'KM', en: 'The Comoros', zh: '科摩罗'},
      {code: 'KN', en: 'St. Kitts & Nevis', zh: '圣基茨和尼维斯'},
      {code: 'KP', en: 'North Korea', zh: '朝鲜'},
      {code: 'KR', en: 'South Korea', zh: '韩国'},
      {code: 'KW', en: 'Kuwait', zh: '科威特'},
      {code: 'KY', en: 'Cayman Islands', zh: '开曼群岛'},
      {code: 'KZ', en: 'Kazakhstan', zh: '哈萨克斯坦'},
      {code: 'LA', en: 'Laos', zh: '老挝'},
      {code: 'LB', en: 'Lebanon', zh: '黎巴嫩'},
      {code: 'LC', en: 'St. Lucia', zh: '圣卢西亚'},
      {code: 'LI', en: 'Liechtenstein', zh: '列支敦士登'},
      {code: 'LK', en: 'Sri Lanka', zh: '斯里兰卡'},
      {code: 'LR', en: 'Liberia', zh: '利比里亚'},
      {code: 'LS', en: 'Lesotho', zh: '莱索托'},
      {code: 'LT', en: 'Lithuania', zh: '立陶宛'},
      {code: 'LU', en: 'Luxembourg', zh: '卢森堡'},
      {code: 'LV', en: 'Latvia', zh: '拉脱维亚'},
      {code: 'LY', en: 'Libya', zh: '利比亚'},
      {code: 'MA', en: 'Morocco', zh: '摩洛哥'},
      {code: 'MC', en: 'Monaco', zh: '摩纳哥'},
      {code: 'MD', en: 'Moldova', zh: '摩尔多瓦'},
      {code: 'ME', en: 'Montenegro', zh: '黑山'},
      {code: 'MF', en: 'Saint Martin (France)', zh: '法属圣马丁'},
      {code: 'MG', en: 'Madagascar', zh: '马达加斯加'},
      {code: 'MH', en: 'Marshall islands', zh: '马绍尔群岛'},
      {code: 'MK', en: 'Republic of Macedonia (FYROM)', zh: '马其顿'},
      {code: 'ML', en: 'Mali', zh: '马里'},
      {code: 'MM', en: 'Myanmar (Burma)', zh: '缅甸'},
      {code: 'MN', en: 'Mongolia', zh: '蒙古国'},
      {code: 'MP', en: 'Northern Mariana Islands', zh: '北马里亚纳群岛'},
      {code: 'MQ', en: 'Martinique', zh: '马提尼克'},
      {code: 'MR', en: 'Mauritania', zh: '毛里塔尼亚'},
      {code: 'MS', en: 'Montserrat', zh: '蒙塞拉特岛'},
      {code: 'MT', en: 'Malta', zh: '马耳他'},
      {code: 'MU', en: 'Mauritius', zh: '毛里求斯'},
      {code: 'MV', en: 'Maldives', zh: '马尔代夫'},
      {code: 'MW', en: 'Malawi', zh: '马拉维'},
      {code: 'MX', en: 'Mexico', zh: '墨西哥'},
      {code: 'MY', en: 'Malaysia', zh: '马来西亚'},
      {code: 'MZ', en: 'Mozambique', zh: '莫桑比克'},
      {code: 'NA', en: 'Namibia', zh: '纳米比亚'},
      {code: 'NC', en: 'New Caledonia', zh: '新喀里多尼亚'},
      {code: 'NE', en: 'Niger', zh: '尼日尔'},
      {code: 'NF', en: 'Norfolk Island', zh: '诺福克岛'},
      {code: 'NG', en: 'Nigeria', zh: '尼日利亚'},
      {code: 'NI', en: 'Nicaragua', zh: '尼加拉瓜'},
      {code: 'NL', en: 'Netherlands', zh: '荷兰'},
      {code: 'NO', en: 'Norway', zh: '挪威'},
      {code: 'NP', en: 'Nepal', zh: '尼泊尔'},
      {code: 'NR', en: 'Nauru', zh: '瑙鲁'},
      {code: 'NU', en: 'Niue', zh: '纽埃'},
      {code: 'NZ', en: 'New Zealand', zh: '新西兰'},
      {code: 'OM', en: 'Oman', zh: '阿曼'},
      {code: 'PA', en: 'Panama', zh: '巴拿马'},
      {code: 'PE', en: 'Peru', zh: '秘鲁'},
      {code: 'PF', en: 'French polynesia', zh: '法属波利尼西亚'},
      {code: 'PG', en: 'Papua New Guinea', zh: '巴布亚新几内亚'},
      {code: 'PH', en: 'The Philippines', zh: '菲律宾'},
      {code: 'PK', en: 'Pakistan', zh: '巴基斯坦'},
      {code: 'PL', en: 'Poland', zh: '波兰'},
      {code: 'PM', en: 'Saint-Pierre and Miquelon', zh: '圣皮埃尔和密克隆'},
      {code: 'PN', en: 'Pitcairn Islands', zh: '皮特凯恩群岛'},
      {code: 'PR', en: 'Puerto Rico', zh: '波多黎各'},
      {code: 'PS', en: 'Palestinian territories', zh: '巴勒斯坦'},
      {code: 'PT', en: 'Portugal', zh: '葡萄牙'},
      {code: 'PW', en: 'Palau', zh: '帕劳'},
      {code: 'PY', en: 'Paraguay', zh: '巴拉圭'},
      {code: 'QA', en: 'Qatar', zh: '卡塔尔'},
      {code: 'RE', en: 'Réunion', zh: '留尼汪'},
      {code: 'RO', en: 'Romania', zh: '罗马尼亚'},
      {code: 'RS', en: 'Serbia', zh: '塞尔维亚'},
      {code: 'RU', en: 'Russian Federation', zh: '俄罗斯'},
      {code: 'RW', en: 'Rwanda', zh: '卢旺达'},
      {code: 'SA', en: 'Saudi Arabia', zh: '沙特阿拉伯'},
      {code: 'SB', en: 'Solomon Islands', zh: '所罗门群岛'},
      {code: 'SC', en: 'Seychelles', zh: '塞舌尔'},
      {code: 'SD', en: 'Sudan', zh: '苏丹'},
      {code: 'SE', en: 'Sweden', zh: '瑞典'},
      {code: 'SG', en: 'Singapore', zh: '新加坡'},
      {code: 'SH', en: 'St. Helena & Dependencies', zh: '圣赫勒拿'},
      {code: 'SI', en: 'Slovenia', zh: '斯洛文尼亚'},
      {code: 'SJ', en: 'Svalbard and Jan Mayen', zh: '斯瓦尔巴群岛和扬马延岛'},
      {code: 'SK', en: 'Slovakia', zh: '斯洛伐克'},
      {code: 'SL', en: 'Sierra Leone', zh: '塞拉利昂'},
      {code: 'SM', en: 'San Marino', zh: '圣马力诺'},
      {code: 'SN', en: 'Senegal', zh: '塞内加尔'},
      {code: 'SO', en: 'Somalia', zh: '索马里'},
      {code: 'SR', en: 'Suriname', zh: '苏里南'},
      {code: 'SS', en: 'South Sudan', zh: '南苏丹'},
      {code: 'ST', en: 'Sao Tome & Principe', zh: '圣多美和普林西比'},
      {code: 'SV', en: 'El Salvador', zh: '萨尔瓦多'},
      {code: 'SX', en: 'Sint Maarten', zh: '荷属圣马丁'},
      {code: 'SY', en: 'Syria', zh: '叙利亚'},
      {code: 'SZ', en: 'Swaziland', zh: '斯威士兰'},
      {code: 'TC', en: 'Turks & Caicos Islands', zh: '特克斯和凯科斯群岛'},
      {code: 'TD', en: 'Chad', zh: '乍得'},
      {code: 'TF', en: 'French Southern Territories', zh: '法属南部领地'},
      {code: 'TG', en: 'Togo', zh: '多哥'},
      {code: 'TH', en: 'Thailand', zh: '泰国'},
      {code: 'TJ', en: 'Tajikistan', zh: '塔吉克斯坦'},
      {code: 'TK', en: 'Tokelau', zh: '托克劳'},
      {code: 'TL', en: 'Timor-Leste (East Timor)', zh: '东帝汶'},
      {code: 'TM', en: 'Turkmenistan', zh: '土库曼斯坦'},
      {code: 'TN', en: 'Tunisia', zh: '突尼斯'},
      {code: 'TO', en: 'Tonga', zh: '汤加'},
      {code: 'TR', en: 'Turkey', zh: '土耳其'},
      {code: 'TT', en: 'Trinidad & Tobago', zh: '特立尼达和多巴哥'},
      {code: 'TV', en: 'Tuvalu', zh: '图瓦卢'},
      {code: 'TZ', en: 'Tanzania', zh: '坦桑尼亚'},
      {code: 'UA', en: 'Ukraine', zh: '乌克兰'},
      {code: 'UG', en: 'Uganda', zh: '乌干达'},
      {code: 'UM', en: 'United States Minor Outlying Islands', zh: '美国本土外小岛屿'},
      {code: 'UY', en: 'Uruguay', zh: '乌拉圭'},
      {code: 'UZ', en: 'Uzbekistan', zh: '乌兹别克斯坦'},
      {code: 'VA', en: 'Vatican City (The Holy See)', zh: '梵蒂冈'},
      {code: 'VC', en: 'St. Vincent & the Grenadines', zh: '圣文森特和格林纳丁斯'},
      {code: 'VE', en: 'Venezuela', zh: '委内瑞拉'},
      {code: 'VG', en: 'British Virgin Islands', zh: '英属维尔京群岛'},
      {code: 'VI', en: 'United States Virgin Islands', zh: '美属维尔京群岛'},
      {code: 'VN', en: 'Vietnam', zh: '越南'},
      {code: 'VU', en: 'Vanuatu', zh: '瓦努阿图'},
      {code: 'WF', en: 'Wallis and Futuna', zh: '瓦利斯和富图纳'},
      {code: 'WS', en: 'Samoa', zh: '萨摩亚'},
      {code: 'YE', en: 'Yemen', zh: '也门'},
      {code: 'YT', en: 'Mayotte', zh: '马约特'},
      {code: 'ZA', en: 'South Africa', zh: '南非'},
      {code: 'ZM', en: 'Zambia', zh: '赞比亚'},
      {code: 'ZW', en: 'Zimbabwe', zh: '津巴布韦'}
    ]
    this.Type = [
      {code: 'L-R', en: 'Learn', zh: '学习'},
      {code: 'T-S', en: 'tourism', zh: '旅游'},
      {code: 'K-T-V', en: 'KTV', zh: 'KTV'},
      {code: 'B-R', en: 'Bar', zh: '酒吧'},
      {code: 'S-P-A', en: 'SPA', zh: '水疗'},
      {code: 'O-E', en: 'other', zh: '其他'}
    ]
    this.lang = Cookies.get('language') || 'zh'
  }
  createPlayer () {
    this.nation.forEach((element, index) => {
      element.children = []
      if (this.lang === 'zh') {
        element.value = element.code
        element.label = element.zh
        this.Type.forEach((item, i) => {
          item.value = item.code
          item.label = item.zh
          element.children.push(item)
        })
      } else {
        element.value = element.code
        element.label = element.en
        this.Type.forEach((item, i) => {
          item.value = item.code
          item.label = item.en
          element.children.push(item)
        })
      }
    })
    return this.nation
  }
  createType () {
    this.Type.forEach((item, i) => {
      if (this.lang === 'zh') {
        item.value = item.code
        item.label = item.zh
      } else {
        item.value = item.code
        item.label = item.en
      }
    })
    return this.Type
  }
}
export default Country
